const GLASS_TYPES = [
  'Balloon Glass',
  'Beer Glass',
  'Beer mug',
  'Beer pilsner',
  'Brandy snifter',
  'Champagne flute',
  'Cocktail glass',
  'Coffee mug',
  'Collins glass',
  'Copper Mug',
  'Cordial glass',
  'Coupe Glass',
  'Highball glass',
  'Hurricane glass',
  'Irish coffee cup',
  'Jar',
  'Margarita glass',
  'Margarita/Coupette glass',
  'Martini Glass',
  'Mason jar',
  'Nick and Nora Glass',
  'Old-fashioned glass',
  'Parfait glass',
  'Pint glass',
  'Pitcher',
  'Pousse cafe glass',
  'Punch bowl',
  'Shot glass',
  'Whiskey sour glass',
  'White wine glass',
  'Wine Glass',
]

export default GLASS_TYPES
