const INGREDIENTS = {
  
  $$: [
    '151 proof rum',
    '7-up'
  ],

  A: [
    'Absinthe',
    'Absolut citron',
    'Absolut Kurant',
    'Absolut Peppar',
    'Absolut Vodka',
    'Advocaat',
    'Aejo rum',
    'Aftershock',
    'Agave syrup',
    'Ale',
    'Allspice',
    'Almond Extract',
    'Almond flavoring',
    'Almond',
    'Amaretto',
    'Angelica Root',
    'Angostura Bitters',
    'Anis',
    'Anise',
    'Anisette',
    'Aperol',
    'Apfelkorn',
    'Apple Brandy',
    'Apple Cider',
    'Apple Juice',
    'Apple schnapps',
    'Apple',
    'Applejack',
    'Apricot Brandy',
    'Apricot nectar',
    'Apricot',
    'Aquavit',
    'Asafoetida',
    'A?ejo rum',
  ],

  B: [
    'Baby Plum Tomatoes',
    'Bacardi Limon',
    'Bacardi',
    'Bacon',
    ['Bailey', '\'', 's irish cream'].join(''),
    'Baileys irish cream',
    'Banana liqueur',
    'Banana rum',
    'Banana syrup',
    'Banana',
    'Barenjager',
    'Basil',
    'Beef bouillon',
    'Beef Stock',
    'Beer',
    'Benedictine',
    'Berries',
    'Bitter lemon',
    'Bitters',
    'Black Pepper',
    'Black rum',
    'Black Sambuca',
    'Blackberries',
    'Blackberry Brandy',
    'Blackberry schnapps',
    'Blackcurrant cordial',
    'Blackcurrant schnapps',
    'Blackcurrant squash',
    'Blended Whiskey',
    'Blue Curacao',
    'Blue Maui',
    'Blueberries',
    'Blueberry schnapps',
    'Bourbon',
    'Bow Tie Pasta',
    'Bramley Apples',
    'Brandy',
    'Bread',
    'Brown Rice',
    'Brown Sugar',
    'Butter, softened',
    'Butter',
    'Butterscotch schnapps',
  ],

  C: [
    'Cachaca',
    'Calvados',
    'Campari',
    'Canadian whisky',
    'Candy',
    'Cantaloupe',
    'Caramel coloring',
    'Carbonated soft drink',
    'Carbonated water',
    'Cardamom',
    'Carrot',
    'Caster Sugar',
    'Cayenne pepper',
    'Celery salt',
    'Celery',
    'Chambord raspberry liqueur',
    'Champagne',
    'Cheese',
    'Cherries',
    'Cherry Brandy',
    'Cherry cola',
    'Cherry Grenadine',
    'Cherry Heering',
    'Cherry juice',
    'Cherry liqueur',
    'Cherry',
    'Chicken Breasts',
    'Chicken Stock',
    'Chicken',
    'Chilled Butter',
    'Chinese Broccoli',
    'Chocolate ice-cream',
    'Chocolate liqueur',
    'Chocolate milk',
    'Chocolate syrup',
    'Chocolate',
    'Chopped Garlic',
    'Chopped Onion',
    'Chopped Tomatoes',
    'Cider',
    'Cinnamon schnapps',
    'Cinnamon',
    'Citrus vodka',
    'Clamato juice',
    'Clove',
    'Cloves',
    'Club Soda',
    'Coca-Cola',
    'Cocktail Olive',
    'Cocktail onion',
    'Cocoa Powder',
    'Coconut cream',
    'Coconut liqueur',
    'Coconut Milk',
    'Coconut rum',
    'Coconut syrup',
    'Coffee brandy',
    'Coffee liqueur',
    'Coffee',
    'Coffeemate',
    'Cognac',
    'Cointreau',
    'Cola',
    'Cold Water',
    'Condensed milk',
    'Coriander Leaves',
    'Coriander',
    'Corn Starch',
    'Corn syrup',
    'Corn Tortillas',
    'Cornstarch',
    'Corona',
    'Courgette',
    'Cranberries',
    'Cranberry Juice',
    'Cranberry liqueur',
    'Cranberry vodka',
    'Cream of Coconut',
    'Cream Sherry',
    'Cream soda',
    'Cream',
    'Creme de Almond',
    'Creme De Banane',
    'Creme de Cacao',
    'Creme de Cassis',
    'Creme de Noyaux',
    'Creme Fraiche',
    'Crown Royal',
    'Crystal light',
    'Cubed Feta Cheese',
    'Cucumber',
    'Cumin powder',
    'Cumin seed',
    'Curacao',
    'Cynar',
  ],

  D: [
    'Daiquiri mix',
    'Dark Chocolate',
    'Dark Creme de Cacao',
    'Dark Rum',
    'Dark Soy Sauce',
    'demerara sugar',
    'Digestive Biscuits',
    'Dijon Mustard',
    'Doner Meat',
    'Dr Pepper',
    'Dr. Pepper',
    'Drambuie',
    'Dried Oregano',
    'Dry Vermouth',
    'Dubonnet blanc',
    'Dubonnet Rouge',
  ],

  E: [
    'Egg White',
    'Egg Yolk',
    'Egg',
    'Eggnog',
    'Eggs',
    'Enchilada Sauce',
    'English Mustard-Small .png',
    'Erin Cream',
    'Espresso',
    'Everclear',
    'Extra Virgin Olive Oil',
  ],

  F: [
    'Fanta',
    'Farfalle',
    'Fennel Seeds',
    'Feta Cheese',
    'Firewater',
    'Flaked Almonds',
    'Flour',
    'Food coloring',
    'Forbidden Fruit',
    'Frangelico',
    'Free-range Egg, Beaten',
    'Free-range Eggs, Beaten',
    'Fresca',
    'Fresh Basil',
    'Fresh Lemon Juice',
    'Freshly Chopped Parsley',
    'Fries',
    'Fruit juice',
    'Fruit punch',
    'Fruit',
  ],

  G: [
    'Galliano',
    'Garlic Sauce',
    'Garlic',
    'Gatorade',
    'Gin',
    'Ginger Ale',
    'Ginger beer',
    'Ginger',
    'Glycerine',
    'Godiva liqueur',
    'Gold rum',
    'Gold Tequila',
    'Goldschlager',
    'Gouda Cheese',
    'Grain Alcohol',
    'Grand Marnier',
    'Granulated Sugar',
    'Grape juice',
    'Grape soda',
    'Grapefruit Juice',
    'Grapes',
    'Grated Cheese',
    'Green Chartreuse',
    'Green Creme de Menthe',
    'Green Ginger Wine',
    'Green Olives',
    'Green Red Lentils',
    'Grenadine',
    'Ground Almonds',
    'Ground Ginger',
    'Guava juice',
    'Guinness stout',
    'Guinness',
  ],

  H: [
    'Half-and-half',
    'Hawaiian punch',
    'Hazelnut liqueur',
    'Heavy cream',
    'Honey',
    'Hooch',
    'Hoopers Hooch',
    'Hot Beef Stock',
    'Hot Chocolate',
    'Hot Damn',
    'Hot Sauce',
    'Hotsauce',
    'Hpnotiq',
  ],

  I: [
    'Ice-Cream',
    'Ice',
    'Iced tea',
    'Irish cream',
    'Irish Whiskey',
    'Italian Seasoning',
  ],

  J: [
    'Jack Daniels',
    'Jello',
    'Jelly',
    'Jagermeister',
    'Jim Beam',
    'Johnnie Walker',
  ],

  K: [
    'Kahlua',
    'Key Largo Schnapps',
    'Kirschwasser',
    'Kiwi liqueur',
    'Kiwi',
    'Kool-Aid',
    'Kummel',
  ],

  L: [
    'Lager',
    'Lasagne Sheets',
    'Lasagne',
    'Lean Minced Beef',
    'Lemon Juice',
    'Lemon Peel',
    'Lemon soda',
    'Lemon vodka',
    'Lemon-lime soda',
    'lemon-lime',
    'lemon',
    'Lemonade',
    'Lentils',
    'Lettuce',
    'Licorice Root',
    'Light Cream',
    'Light Rum',
    'Lillet',
    'Lime juice cordial',
    'Lime Juice',
    'Lime liqueur',
    'Lime peel',
    'Lime vodka',
    'Lime',
    'Limeade',
  ],

  M: [
    'Madeira',
    'Malibu Rum',
    'Malt Vinegar',
    'Mandarin',
    'Mandarine napoleon',
    'Mango',
    'Maple syrup',
    'Maraschino cherry juice',
    'Maraschino Cherry',
    'Maraschino Liqueur',
    'Margarita mix',
    'Marjoram leaves',
    'Marshmallows',
    'Maui',
    'Melon liqueur',
    'Melon vodka',
    'Mezcal',
    'Midori melon liqueur',
    'Midori-Small .png',
    'Milk',
    'Minced Beef',
    'Minced Garlic',
    'Mint syrup',
    'Mint',
    'Mountain Dew',
    'Mozzarella Balls',
    'Mozzarella',
    'Mushroom',
    'Mushrooms',
    'Mustard',
  ],

  N: [
    'Nutmeg',
    'Nuts',
  ],
  
  O: [
    'Olive Oil',
    'Onion',
    'Olive',
    'Onions',
    'Orange Bitters',
    'Orange Curacao',
    'Orange Juice',
    'Orange liqueur',
    'Orange Peel',
    'Orange rum',
    'Orange Soda',
    'Orange spiral',
    'Orange vodka',
    'Orange',
    'Oregano',
    'Oreo cookie',
    'Orgeat Syrup',
    'Ouzo',
    'Oyster Sauce',
  ],

  P: [
    'Papaya juice',
    'Papaya',
    `Parfait d${'\''}amour`,
    'Parmesan Cheese',
    'Parmesan',
    'Parmigiano-Reggiano',
    'Parsley',
    'Passion fruit juice',
    'Passion fruit syrup',
    'Passoa',
    'Peach brandy',
    'Peach juice',
    'Peach liqueur',
    'Peach Nectar',
    'Peach Schnapps',
    'Peach Vodka',
    'Peach',
    'Peachtree schnapps',
    'Peanut Oil',
    'Peas',
    'Penne Rigate',
    'Pepper',
    'Peppermint extract',
    'Peppermint Schnapps',
    'Pepsi Cola',
    'Pernod',
    'Peychaud bitters',
    'Pina colada mix',
    'Pineapple Juice',
    'Pineapple rum',
    'Pineapple vodka',
    'Pineapple-orange-banana juice',
    'Pineapple',
    'Pink lemonade',
    'Pisang Ambon',
    'Pisco',
    'Pi?a colada',
    'Plain Chocolate',
    'Plain Flour',
    'Plum Tomatoes',
    'Plums',
    'Port',
    'Potato',
    'Potatoes',
    'Powdered Sugar',
    'Prawns',
    'Purple passion',
  ],

  R: [
    'Raisins',
    'Raspberry cordial',
    'Raspberry Jam',
    'Raspberry juice',
    'Raspberry liqueur',
    'Raspberry schnapps',
    'Raspberry syrup',
    'Raspberry Vodka',
    'Raw King Prawns',
    'Red Chile Flakes',
    'Red Chili Flakes',
    'Red Hot Chili Flakes',
    'Red Lentils',
    'Red Wine',
    'Rhubarb',
    'Ricard',
    'Rice Stick Noodles',
    'Rock Salt',
    'Root beer schnapps',
    'Root beer',
    'Roses sweetened lime juice',
    'Rosewater',
    'Rum',
    'Rumple Minze',
    'Rye whiskey',
  ],

  S: [
    'Sake',
    'Salmon',
    'Salt',
    'Sambuca',
    'Sarsaparilla',
    'Schnapps',
    'Schweppes Lemon',
    'Schweppes Russchian',
    'Schweppes Russchiani',
    'Scotch',
    'Sesame Seed',
    'Sherbet',
    'Sherry',
    'Shredded Cheese',
    'Shredded Monterey Jack Cheese',
    'Sirup of roses',
    'Sloe Gin',
    'Small.png',
    'Soda Water',
    'Sour Apple Pucker',
    'Sour Mix',
    'Southern Comfort',
    'Soy Milk',
    'Soy Sauce',
    'Soya Milk',
    'Soya Sauce',
    'Spaghetti',
    'Spiced Rum',
    'Spinach',
    'Sprite',
    'Squeezed Orange',
    'Squirt',
    'Stir-fry Vegetables',
    'Strawberries',
    'Strawberry juice',
    'Strawberry liqueur',
    'Strawberry Schnapps',
    'Strawberry syrup',
    'Sugar Syrup',
    'Sugar',
    'Sunny delight',
    'Surge',
    'Swedish punch',
    'Sweet and Sour',
    'Sweet Cream',
    'Sweet Vermouth',
  ],

  T: [
    'Tabasco Sauce',
    'Tang',
    'Tawny port',
    'Tea',
    'Tennessee whiskey',
    'Tequila rose',
    'Tequila',
    'Tia Maria',
    'Tinned Tuna',
    'Tomato Juice',
    'Tomato Puree',
    'Tomato',
    'Tomatoe',
    'Tomatoes',
    'Tonic Water',
    'Triple Sec',
    'Tropicana',
    'Tuaca',
    'Tuna',
  ],

  V: [
    'Vanilla extract',
    'Vanilla Ice-Cream',
    'Vanilla liqueur',
    'Vanilla schnapps',
    'Vanilla syrup',
    'Vanilla vodka',
    'Vanilla',
    'Vegan Butter',
    'Vermouth',
    'Vinegar',
    'Vodka',
  ],

  W: [
    'Water',
    'Watermelon schnapps',
    'Whipped Cream',
    'Whipping Cream',
    'Whiskey',
    'Whisky',
    'White chocolate liqueur',
    'White Creme de Menthe',
    'White grape juice',
    'White port',
    'White Rum',
    'White Vinegar',
    'White Wine',
    'Wild Turkey',
    'Wildberry schnapps',
    'Wine',
    'Worcestershire Sauce',
    'Wormwood',
  ],

  Y: [
    'Yeast',
    'Yellow Chartreuse',
    'Yoghurt',
    'Yukon Jack'
  ],

  Z: [
    'Zima',
    'Zucchini'
  ],
  
}

export default INGREDIENTS
